apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: my-node-pool
spec:
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: private-compute
      requirements:
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["t"]
        - key: "eks.amazonaws.com/instance-generation"
          operator: In
          values: ["4"]
        - key: "eks.amazonaws.com/instance-size"
          operator: In
          values: ["medium"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
  limits:
    cpu: 4
    memory: 8Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s